spring.application.name=iniato



spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
  spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=postgres
spring.datasource.password=First#1234
spring.datasource.driver-class-name=org.postgresql.Driver



jwt.secret=G7Dq1+Z7SxtSgfSUv6qk4vY5pJhVu1JHj2zI6+LYRJk=


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

twilio.account-sid=AC1d7cfb4fa2601a6d14a9844dcaa19a4e
twilio.auth-token=2f90f985a148dea856282839411ff366
twilio.verify-service-sid=US7e83b599490991f4c3debaf4a896b005