spring.application.name=iniato

server.port=8081

# ─── PostgreSQL ──────────────────────────────────────────────────────────────
spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=postgres
spring.datasource.password=First#1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ─── PostGIS: auto-create extension on startup ──────────────────────────────
spring.jpa.properties.hibernate.hbm2ddl.import_files=import.sql

# ─── Redis ───────────────────────────────────────────────────────────────────
spring.data.redis.host=localhost
spring.data.redis.port=6379

# ─── JWT ─────────────────────────────────────────────────────────────────────
jwt.secret=G7Dq1+Z7SxtSgfSUv6qk4vY5pJhVu1JHj2zI6+LYRJk=

# ─── Twilio OTP ──────────────────────────────────────────────────────────────
twilio.account-sid=AC1d7cfb4fa2601a6d14a9844dcaa19a4e
twilio.auth-token=373d9633a59163af6565171dc995c180
twilio.verify-service-sid=VA847dd1611b2331436927daf0a7e83c00